### ISSUE TITLE
addTarget(mixed $target)  always send active flag to VWS

### ISSUE THREAD

**Issue by Soulreavertom** [Eyesar/laravel-vuforia#2]
From PHP Manual – empty():
empty — Determine whether a variable is empty
In other words, it will return true if the variable is an empty string, **false**, array(), NULL, “0?, 0, and an unset variable.

From PHP manual – isset():
isset — Determine if a variable is set and is not NULL
In other words, it returns true only when the variable is not null.

VuforiaWebService.php
public function jsonSerialize() {
        
        $array = [];

        if(!empty($this->name)) {
            $array['name'] = $this->name;
        }

        if(!empty($this->width)) {
            $array['width'] = $this->width;
        }

        if(!empty($this->image)) {
            $array['image'] = base64_encode($this->image);
        }

//if(!empty($this->active)) {  //when you send false in $this->active the empty function will return true and never go in to set  the $array['active_flag'], with isset  the issue is solved.
        if(isset($this->active)) {
            $array['active_flag'] = $this->active ? 1 : 0;
        }
        
        if(!empty($this->metadata)) {
            $array['application_metadata'] = base64_encode($this->metadata);
        }
        return $array;
    }

**Comment by seancheung** [comment]
thanks. you may open a pull request or I'll fix it later

**Comment by seancheung** [comment]
Solved. You may get the latest release now.
