### ISSUE TITLE
Class 'Panoscape\Vuforia\Target' not found

### ISSUE THREAD

**Issue by marcoapferegrino** [Eyesar/laravel-vuforia#3]
I include 

use Panoscape\Vuforia\Target;

but the menssage 

Class 'Panoscape\Vuforia\Target' not found

appears

**Comment by seancheung** [comment]
Maybe you should run  `composer dump-autoload`.

**Comment by marcoapferegrino** [comment]
I did, and reinstall but the facade is not recognised

**Comment by seancheung** [comment]
It's weird.

- Make sure *vendor/panoscape/laravel-vuforia/src* exists.
- Try use root namespace `use \Panoscape\Vuforia\Target;`

If still not working, please post your **composer.json** file

**Comment by marcoapferegrino** [comment]
Yes i did, in fact facade isn't recognized too. The files exists.

**Comment by seancheung** [comment]
It might be your personal setup problem.
Not an issue.
