### ISSUE TITLE
Not available for Laravel framework v5.4.16

### ISSUE THREAD

**Issue by marcoapferegrino** [Eyesar/laravel-vuforia#4]
Hi Friend I was using you package and is aweasome ! Thanks, but now I upgrade L5.4 I got this mesage. Is some solution for this ? 

Conclusion: remove laravel/framework v5.4.16
    - Conclusion: don't install laravel/framework v5.4.16
    - panoscape/laravel-vuforia 1.0.1 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - panoscape/laravel-vuforia 1.0.2 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - panoscape/laravel-vuforia v1.0.0 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.16
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.16
    - Installation request for laravel/framework (locked at v5.4.16, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.16].
    - Installation request for panoscape/laravel-vuforia ^1.0 -> satisfiable by panoscape/laravel-vuforia[1.0.1, 1.0.2, v1.0.0].

**Comment by seancheung** [comment]
It's not updated to be compatible with Laravel 5.4 yet.
I'll fix it later soon.

**Comment by marcoapferegrino** [comment]
Thanks friend. Excelent Job.

**Comment by seancheung** [comment]
Added support for Laravel 5.4 in v1.1.0

**Comment by marcoapferegrino** [comment]
Thanks that was really fast
