### ISSUE TITLE
Laravel 5.6 support ?

### ISSUE THREAD

**Issue by ghost** [Eyesar/laravel-vuforia#6]
Hi,

i tried to install it with composer but i have an error : 
Your requirements could not be resolved to an installable set of packages.

I have Laravel 5.6.29. Do i need something special when installing ?

Thanks in advance :-)

**Comment by seancheung** [comment]
Hi this package hasn't been tested with Laravel 5.6 yet.
So it supports up to 5.5 at the moment.

Will check soon.

**Comment by ghost** [comment]
Ok, nice :-) !

Thanks a lot !

**Comment by seancheung** [comment]
Updated

**Comment by ghost** [comment]
Nice, it's working ! Thx :)
